name: create_basin_mask
channels:
  - conda-forge
dependencies:
  - cartopy
  - gdal
  - matplotlib
  - netCDF4
  - numpy
  - pip
  - pyproj
  - pyyaml
  - scipy
  - setuptools_scm
  - pandas
  - geopandas
  - rasterio
  - xarray
  - flake8
  - pytest
  - pydantic
  - pytest-cov
  - pip:
     - git+https://github.com/ppinard/matplotlib-scalebar.git